accounttransactions:
  property: AccountTransactions Profile Dev
server:
  port: 8097
spring:
  data:
    mongodb:
      url: mongodb+srv://admin:admin@elucia.geg2xq0.mongodb.net/?retryWrites=true&w=majority
      database: Transactions
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost