spring:
  data:
    mongodb:
      url : mongodb+srv://admin:<password>@elucia.geg2xq0.mongodb.net/?retryWrites=true&w=majority
      database : Accounts

cloud:
  config:
    server:
      git:
        uri: https://github.com/eluciaa/service-configuration
        default-label: master
        clone-on-start: true