spring:
  data:
    mongodb:
      #uri: mongodb+srv://admin:admin@elucia.geg2xq0.mongodb.net/?retryWrites=true&w=majority
      uri: mongodb://localhost:27017/accounts
      host: localhost
      port: 27017
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true