spring:
  data:
    mongodb:
      url : mongodb+srv://dev:az9Y7tr5eGTgHzVF@nttdata.tipkdvn.mongodb.net/bootcamp?retryWrites=true&w=majority
      database : Accounts

cloud:
  config:
    server:
      git:
        uri: https://github.com/eluciaa/service-configuration
        default-label: master
        clone-on-start: true