version: "3"

services:

  ms-configserver:
    container_name: ms-configserver
    build:
      context: ../ms-configserver
      dockerfile: Dockerfile
    image: ms-configserver
    ports:
      - "8091:8091"
    networks:
      team:
        aliases:
          - ms-configserver

  ms-eurekaserver:
    container_name: ms-eurekaserver
    build:
      context: ../ms-eurekaserver
      dockerfile: Dockerfile
    image: ms-eurekaserver
    environment:
      - spring.cloud.config.uri= http://ms-configserver:8091
    ports:
      - "8761:8761"
    depends_on:
      - ms-configserver
    networks:
      - team

  ms-gateway:
    container_name: ms-gateway
    build:
      context: ../ms-gateway
      dockerfile: Dockerfile
    image: ms-gateway
    environment:
      - spring.cloud.config.uri= http://ms-configserver:8091
      - eureka.client.serviceUrl.defaultZone=http://ms-eurekaserver:8761/eureka
    ports:
      - "8081:8081"
    depends_on:
      - ms-eurekaserver
    networks:
      - team

  ms-customer:
    container_name: ms-customer
    build:
      context: ../ms-customer
      dockerfile: Dockerfile
    image: ms-customer
    environment:
      - spring.cloud.config.uri= http://ms-configserver:8091
      - eureka.client.serviceUrl.defaultZone=http://ms-eurekaserver:8761/eureka
    depends_on:
      - ms-eurekaserver
      - ms-gateway
    networks:
      - team

  ms-bankaccount:
    image: ms-bankaccount
    environment:
      - eureka.client.serviceUrl.defaultZone=http://ms-eurekaserver:8761/eureka
    ports:
      - "8700:8700"
    depends_on:
      - ms-eurekaserver
      - ms-gateway
    networks:
      - team

  ms-credit:
    image: ms-credit
    environment:
      - eureka.client.serviceUrl.defaultZone=http://ms-eurekaserver:8761/eureka
    ports:
      - "8701:8701"
    depends_on:
      - ms-eurekaserver
      - ms-gateway
    networks:
      - team

  ms-debit:
    image: ms-debit
    environment:
      - eureka.client.serviceUrl.defaultZone=http://ms-eurekaserver:8761/eureka
    ports:
      - "8702:8702"
    depends_on:
      - ms-eurekaserver
      - ms-gateway
    networks:
      - team

networks:
  team:
    driver: bridge