version: "3"

services:

  ms-configserver:
    container_name: ms-configserver
    build:
      context: ../ms-configserver
      dockerfile: Dockerfile
    image: ms-configserver
    ports:
      - "8091:8091"
    healthcheck:
      test: curl -f http://ms-configserver:8091/actuator/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - team

  ms-eurekaserver:
    container_name: ms-eurekaserver
    build:
      context: ../ms-eurekaserver
      dockerfile: Dockerfile
    image: ms-eurekaserver
    environment:
      - spring.cloud.config.uri= http://ms-configserver:8091
    ports:
      - "8761:8761"
    healthcheck:
      test: curl -f http://ms-eurekaserver:8761/actuator/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      ms-configserver:
        condition: service_healthy
    networks:
      - team

  ms-gateway:
    container_name: ms-gateway
    build:
      context: ../ms-gateway
      dockerfile: Dockerfile
    image: ms-gateway
    environment:
      - spring.cloud.config.uri= http://ms-configserver:8091
      - eureka.client.serviceUrl.defaultZone=http://ms-eurekaserver:8761/eureka
    ports:
      - "8081:8081"
    depends_on:
      ms-eurekaserver:
        condition: service_healthy
    networks:
      - team

  ms-customer:
    container_name: ms-customer
    build:
      context: ../ms-customer
      dockerfile: Dockerfile
    image: ms-customer
    environment:
      - spring.profiles.active= docker
      - spring.cloud.config.uri= http://ms-configserver:8091
    depends_on:
      ms-eurekaserver:
        condition: service_healthy
      ms-gateway:
        condition: service_started
    networks:
      - team

  ms-bankaccount:
    image: ms-bankaccount
    environment:
      - spring.profiles.active= docker
      - spring.cloud.config.uri= http://ms-configserver:8091
    ports:
      - "8700:8700"
    depends_on:
      ms-eurekaserver:
        condition: service_healthy
      ms-gateway:
        condition: service_started
    networks:
      - team

  ms-credit:
    image: ms-credit
    environment:
      - spring.profiles.active= docker
      - spring.cloud.config.uri= http://ms-configserver:8091
    ports:
      - "8701:8701"
    depends_on:
      ms-eurekaserver:
        condition: service_healthy
      ms-gateway:
        condition: service_started
    networks:
      - team

  ms-debit:
    image: ms-debit
    environment:
      - spring.profiles.active= docker
      - spring.cloud.config.uri= http://ms-configserver:8091
    ports:
      - "8702:8702"
    depends_on:
      ms-eurekaserver:
        condition: service_healthy
      ms-gateway:
        condition: service_started
    networks:
      - team

  ms-monedero:
    image: ms-monedero
    environment:
      - spring.profiles.active= docker
      - spring.cloud.config.uri= http://ms-configserver:8091
    ports:
      - "8703:8703"
    depends_on:
      ms-eurekaserver:
        condition: service_healthy
      ms-gateway:
        condition: service_started
    networks:
      - team

networks:
  team:
    driver: bridge