version: "3"

services:
  ms-configserver:
    image: ms-configserver
    ports:
      - "8091:8091"

  ms-eurekaserver:
    image: ms-eurekaserver
    ports:
      - "8761:8761"
    depends_on:
      - ms-configserver

  ms-gateway:
    image: ms-gateway
    environment:
      - eureka.client.serviceUrl.defaultZone=http://ms-eurekaserver:8761/eureka
    ports:
      - "8081:8081"
    depends_on:
      - ms-eurekaserver

  ms-bankaccount:
    image: ms-bankaccount
    environment:
      - eureka.client.serviceUrl.defaultZone=http://ms-eurekaserver:8761/eureka
    ports:
      - "8700:8700"
    depends_on:
      - ms-eurekaserver
      - ms-gateway