version: "3"

services:

  ms-configserver:
    image: ms-configserver
    ports:
      - "8091:8091"
    networks:
      - test-network

  ms-eurekaserver:
    image: ms-eurekaserver
    ports:
      - "8761:8761"
    depends_on:
      - ms-configserver
    networks:
      - test-network

  ms-gateway:
    image: ms-gateway
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://ms-eurekaserver:8761/eureka
    ports:
      - "8081:8081"
    depends_on:
      - ms-eurekaserver
    networks:
      - test-network

  ms-bankaccount:
    image: ms-bankaccount
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: //ms-eurekaserver:8761/eureka
    ports:
      - "8700:8700"
    depends_on:
      - ms-eurekaserver
      - ms-gateway
    networks:
      - test-network

networks:
  test-network: