server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: bankaccount
          uri: lb://bankaccount
          predicates:
            - Path=/accounts/**
        - id: credit
          uri: lb://credit
          predicates:
            - Path=/credits/**
        - id: statusaccount
          uri: lb://statusaccount
          predicates:
            - Path=/status/**
        - id: customer
          uri: lb://customer
          predicates:
            - Path=/customers/**