server:
  port: 8081
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://host.docker.internal:8761/eureka
  instance:
    hostname: host.docker.internal
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: bankaccount
          uri: lb://bankaccount
          predicates:
            - Path=/accounts/**
        - id: credit
          uri: lb://credit
          predicates:
            - Path=/credits/**
        - id: statusaccount
          uri: lb://statusaccount
          predicates:
            - Path=/status/**
        - id: customer
          uri: lb://customer
          predicates:
            - Path=/customer/**
        - id: movement
          uri: lb://movement
          predicates:
            - Path=/movement/**